namespace Verify.MSTest.SourceGenerator;

static class CodeWriter
{
    private static readonly string AutoGenerationHeader = """
        //-----------------------------------------------------
        // This code was generated by a tool.
        //
        // Changes to this file may cause incorrect behavior
        // and will be lost when the code is regenerated.
        // <auto-generated />
        //-----------------------------------------------------

        """;

    private static readonly string GeneratedCodeAttribute =
        $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{typeof(CodeWriter).Assembly.GetName().Name}, \"{typeof(CodeWriter).Assembly.GetName().Version}\")]";

    private static void WriteNamespace(IndentedStringBuilder sb, ClassToGenerate classToGenerate)
    {
        if (!string.IsNullOrEmpty(classToGenerate.Namespace)) // TODO: Consider making nullable?
        {
            sb.AppendLine($"namespace {classToGenerate.Namespace}");
            sb.AppendLine("{");

            sb.IncreaseIndent();
        }

        WriteParentTypes(sb, classToGenerate);

        if (!string.IsNullOrEmpty(classToGenerate.Namespace)) // TODO: Consider making nullable?
        {
            sb.DecreaseIndent();
            sb.AppendLine("}");
        };
    }

    private static void WriteParentTypes(IndentedStringBuilder sb, ClassToGenerate classToGenerate)
    {
        var parentClass = classToGenerate.ParentClass;
        var depth = 1;
        while (parentClass is not null)
        {
            sb.AppendLine($"partial {parentClass.Keyword} {parentClass.Name}{parentClass.Constraints}");
            sb.AppendLine("{");

            sb.IncreaseIndent();
            depth += 1;
            parentClass = parentClass.Child;
        }

        WriteClass(sb, classToGenerate);

        while (depth < 0)
        {
            sb.DecreaseIndent();
            sb.AppendLine("}");

            depth -= 1;
        }
    }

    private static void WriteClass(IndentedStringBuilder sb, ClassToGenerate classToGenerate)
    {
        var genericConstraints = string.Empty;

        if (classToGenerate.TypeParameters.Count > 0)
        {
            genericConstraints = $"<{string.Join(", ", classToGenerate.TypeParameters)}>";
        }

        sb.AppendLine(GeneratedCodeAttribute);
        sb.AppendLine($"partial class {classToGenerate.ClassName}{genericConstraints}");
        sb.AppendLine("{");
        sb.AppendLine("    public TestContext TestContext");
        sb.AppendLine("    {");
        sb.AppendLine("        get => CurrentTestContext.Value!;");
        sb.AppendLine("        set => CurrentTestContext.Value = value;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    public static string GenerateExtensionClass(ClassToGenerate classToGenerate)
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine(AutoGenerationHeader);

        WriteNamespace(sb, classToGenerate);

        return sb.ToString();
    }
}
