namespace Verify.MSTest.SourceGenerator;

static class CodeWriter
{
    private static readonly string AutoGenerationHeader = """
        //-----------------------------------------------------
        // This code was generated by a tool.
        //
        // Changes to this file may cause incorrect behavior
        // and will be lost when the code is regenerated.
        // <auto-generated />
        //-----------------------------------------------------

        """;

    private static readonly string GeneratedCodeAttribute =
        $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{typeof(CodeWriter).Assembly.GetName().Name}\", \"{typeof(CodeWriter).Assembly.GetName().Version}\")]";

    private static void WriteNamespace(IndentedStringBuilder sb, ClassToGenerate classToGenerate)
    {
        if (!string.IsNullOrEmpty(classToGenerate.Namespace)) // TODO: Consider making nullable?
        {
            sb.AppendLine(["namespace ", classToGenerate.Namespace])
              .AppendLine("{")
              .IncreaseIndent();
        }

        WriteParentTypes(sb, classToGenerate);

        if (!string.IsNullOrEmpty(classToGenerate.Namespace)) // TODO: Consider making nullable?
        {
            sb.DecreaseIndent()
              .AppendLine("}");
        };
    }

    private static void WriteParentTypes(IndentedStringBuilder sb, ClassToGenerate classToGenerate)
    {
        var parentClass = classToGenerate.ParentClass;
        var depth = 0;
        while (parentClass is not null)
        {
            sb.AppendLine(["partial ", parentClass.Keyword, " ", parentClass.Name, parentClass.Constraints])
              .AppendLine("{");

            sb.IncreaseIndent();
            depth += 1;
            parentClass = parentClass.Child;
        }

        WriteClass(sb, classToGenerate);

        while (depth > 0)
        {
            sb.DecreaseIndent()
              .AppendLine("}");

            depth -= 1;
        }
    }

    private static void WriteClass(IndentedStringBuilder sb, ClassToGenerate classToGenerate)
    {
        var genericConstraints = string.Empty;

        if (classToGenerate.TypeParameters.Count > 0)
        {
            // TODO: Reimplement for perf
            genericConstraints = $"<{string.Join(", ", classToGenerate.TypeParameters)}>";
        }

        sb.AppendLine(GeneratedCodeAttribute)
          .AppendLine($"partial class {classToGenerate.ClassName}{genericConstraints}") // TODO: Reimplement for perf
          .AppendLine("{")
          .AppendLine("    public TestContext TestContext")
          .AppendLine("    {")
          .AppendLine("        get => CurrentTestContext.Value!;")
          .AppendLine("        set => CurrentTestContext.Value = value;")
          .AppendLine("    }")
          .AppendLine("}");
    }

    public static string GenerateExtensionClass(ClassToGenerate classToGenerate)
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine(AutoGenerationHeader);

        WriteNamespace(sb, classToGenerate);

        return sb.ToString();
    }
}
